In [1]:
import numpy as np

In [4]:
my_1D_array = np.array([1, 2, 3, 4, 5])
print(my_1D_array.shape)   #(5,) -> 1 row and 5 columns

my_2D_array = np.array([[1, 2],[3, 4],[6,5]])
print(my_2D_array.shape)     #(3, 2) -> 3 rows and 2 columns 

(5,)
(3, 2)


In [6]:
change_array = np.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)

#Output
# [[1 2]
# [3 4]
# [5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [8]:
change_array.shape

(3, 2)

In [9]:
change_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
change_array.shape = (1,6)

In [11]:
change_array

array([[1, 2, 3, 4, 5, 6]])

In [12]:
change_array.shape = (6)

In [13]:
change_array.shape 

(6,)

In [14]:
change_array.shape = (6,1)

In [15]:
change_array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
import numpy as np

my_array = np.array([1,2,3,4,5,6])
print(np.reshape(my_array,(3,2)))

#Output
# [[1 2]
# [3 4]
# [5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [17]:
my_array

array([1, 2, 3, 4, 5, 6])

In [35]:
a = "1 2 3 4 5 6 7 8 9"
a = np.array(list(map(int, a.split())))

In [37]:
a.shape = (3,3)

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a = np.array([['4', '2'], ['2', '5'], ['3', '7'], ['1', '3'], ['4', '0']])

In [56]:
a.dtype

dtype('<U1')

In [51]:
a

array([[4., 2.],
       [2., 5.],
       [3., 7.],
       [1., 3.],
       [4., 0.]])

In [46]:
a = [['4' '2'],
 ['2' '5'],
 ['3' '7'],
 ['1' '3'],
 ['4' '0']]

In [47]:
a

[['42'], ['25'], ['37'], ['13'], ['40']]

In [52]:
a

array([[4., 2.],
       [2., 5.],
       [3., 7.],
       [1., 3.],
       [4., 0.]])

In [54]:
a[1:]

array([[2., 5.],
       [3., 7.],
       [1., 3.],
       [4., 0.]])

In [58]:

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

print(np.concatenate((array_1, array_2, array_3)))

#Output
# [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [60]:
np.concatenate((array_1, array_2, array_3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
import numpy as np
np.set_printoptions(legacy='1.13')

In [62]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [65]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])